# Generated by Django 2.1.7 on 2019-04-26 20:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Curso')),
                ('description', models.TextField(verbose_name='Descripcion del curso')),
                ('date_start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Creacion')),
                ('date_end', models.DateTimeField(verbose_name='Fecha de fin de curso')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
