# Generated by Django 2.2.2 on 2019-07-03 18:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_unity'),
    ]

    operations = [
        migrations.AddField(
            model_name='unity',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de fin de unidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unity',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de inicio'),
        ),
    ]
