# Generated by Django 2.2.2 on 2019-07-11 20:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190703_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo del examen')),
                ('date_application', models.DateTimeField(verbose_name='Fecha aplicaion del examen')),
                ('id_unity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Unity')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('date_start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de inicio')),
                ('id_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='respuesta')),
                ('is_correct', models.BooleanField(verbose_name='Es correcta')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Question')),
            ],
        ),
    ]
