# Generated by Django 2.2.3 on 2019-07-18 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_answer_exam_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='tipo'),
            preserve_default=False,
        ),
    ]
